server:
  port: 9080

spring:
  cloud:
    gateway:
      routes:
      - id: apiModule
        uri: http://localhost:8080/
        predicates:
        - Path=/api/**
      - id: webModule
        uri: http://localhost:4000/
        predicates:
        - Path=/**